# Site settings
title: vinyanalista.com.br
email: vinyanalista@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Write an awesome description for your new site here. You can edit this
    line in _config.yml. It will appear in your document head meta (for
    Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.vinyanalista.com.br" # the base hostname & protocol for your site
addthis_profile_id: ra-4f7774466af48b4f
adsense_editor_id: ca-pub-5193467168351289
adsense_ad_unit_1: 4511719452
adsense_ad_unit_2: 5988452654
adsense_ad_unit_3: 7465185857
author: Antônio Vinícius Menezes Medeiros
facebook_username: pages/vinyanalistacombr/1604841683119097
foursquare_username: vinyanalista
github_username: vinyanalista
google_cse_id: 006707575509905065349:opma8i3oclc
google_userid: 117526731689139505675
gravatar_email: vinyanalista@gmail.com
linkedin_username: vinyanalista
twitter_username: vinyanalista
youtube_username: viniciusifse

# Plugins
gems:
    - jekyll-archives
    - jekyll-auto-image
jekyll-archives:
    enabled:
        - year
        - month
        - day
        - categories
    layout: 'archive'
    permalinks:
        year: '/blog/:year/'
        month: '/blog/:year/:month/'
        day: '/blog/:year/:month/:day/'
        category: '/blog/category/:name/'
image: "/favicon.png"

# Build settings
excerpt_separator: <!--more-->
exclude: [online]
markdown: redcarpet

# Paginação
paginate: 10
paginate_path: "/blog/page/:num/"

defaults:
    -
        scope:
            path: ""
            type: "posts"
        values:
            is_post: true # http://stackoverflow.com/questions/18675610/jekyll-change-layout-if-page-is-a-post
            permalink: "/blog/:year/:month/:day/:title/"