# Site settings
title: vinyanalista.com.br
email: vinyanalista@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Write an awesome description for your new site here. You can edit this
    line in _config.yml. It will appear in your document head meta (for
    Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://vinyanalista.github.io" # the base hostname & protocol for your site
addthis_profile_id: ra-4f7774466af48b4f
facebook_username: vinyanalista
foursquare_username: vinyanalista
github_username: vinyanalista
google_userid: 117526731689139505675
linkedin_username: vinyanalista
twitter_username: vinyanalista
youtube_username: viniciusifse

# Build settings
excerpt_separator: <!--more-->
exclude: [online]
markdown: kramdown

# Paginação
category_title_prefix: 'Posts na categoria '
category_dir: "/blog/category/"
paginate: 10
paginate_path: "/blog/page/:num/"

defaults:
    -
        scope:
            path: ""
            type: "posts"
        values:
            permalink: "/blog/:year/:month/:day/:title/"